stages:
  - test

phpcs:
  image: ridibooks/store-php-test:7.1
  stage: test
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
    - composer install --dev
    - vendor/bin/phpcs --standard=ruleset.xml
  cache:
    key: composer
    paths:
      - .composer/cache/
