stages:
  - test

phpcs:
  image: ridibooks/store-php-test:7.1
  stage: test
  script:
    - composer install --dev
    - vendor/bin/phpcs --standard=ruleset.xml
  cache:
    key: composer
    paths:
      - .composer/cache/
